<template><section class="comments"><h2>商品评论</h2><template v-if="loggedIn"><div v-if="identity.level>=2"><el-input v-model="content" type="textarea" :rows="3" maxlength="500" show-word-limit placeholder="分享你的真实体验"/><div v-if="identity.level>=4" class="sticker-picker"><div class="picker-title">专属表情贴纸 <span>点击选择，再次点击取消</span></div><div class="sticker-options"><button v-for="code in ['star','heart','fire','crown']" :key="code" type="button" :class="{selected:emote===code}" :aria-pressed="emote===code" @click="emote=emote===code?null:code"><ExclusiveSticker :code="code"/></button></div></div><div class="post"><span v-if="identity.level>=4" class="decoration-hint">{{identity.level>=5?'♛ 曜黑尊享':'✧ 耀金之声'}} 评论装饰已启用</span><el-button type="primary" :loading="busy" :disabled="!content.trim()" @click="send">发表评论</el-button></div></div><p v-else>LV2 解锁评论。<router-link to="/level">前往等级中心</router-link></p><CommentCard v-for="row in rows" :key="row.id" :row="row"/><el-empty v-if="!rows.length" description="暂无评论"/><el-button v-if="more" :loading="loading" @click="loadMore">加载更多</el-button></template><p v-else>登录后查看和参与评论。</p></section></template>
<script setup>
import {ref,watch} from 'vue'
import {ElMessage} from 'element-plus'
import {getToken} from '@/utils/auth'
import {comments,postComment,levelCenter} from '@/api/level'
import CommentCard from './CommentCard.vue'
import ExclusiveSticker from './ExclusiveSticker.vue'
const props=defineProps({productId:[String,Number]})
const loggedIn=!!getToken(),rows=ref([]),identity=ref({}),content=ref(''),emote=ref(null),busy=ref(false),loading=ref(false),more=ref(true)
async function loadMore(){loading.value=true;try{const res=await comments(props.productId,rows.value.at(-1)?.id||0);rows.value.push(...res.data);more.value=res.data.length===20}catch{}finally{loading.value=false}}
async function send(){busy.value=true;try{await postComment(props.productId,content.value,emote.value);emote.value=null;content.value='';rows.value=[];await loadMore();ElMessage.success('评论已发布')}catch{}finally{busy.value=false}}
watch(()=>props.productId,async()=>{rows.value=[];if(loggedIn){try{identity.value=(await levelCenter()).data;await loadMore()}catch{}}},{immediate:true})
</script>
<style scoped>.comments{background:white;padding:24px;margin-top:24px;border-radius:16px;min-width:0}.post{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-top:16px;flex-wrap:wrap}.decoration-hint{color:#967027;font-size:13px}.sticker-picker{margin-top:14px;padding:14px;border:1px solid #eadab5;border-radius:14px;background:#fffcf5}.picker-title{font-size:14px;font-weight:600;color:#715428}.picker-title span{font-size:12px;font-weight:400;color:#8c8577;margin-left:10px}.sticker-options{display:flex;gap:12px;flex-wrap:wrap;margin-top:14px}.sticker-options button{padding:10px;border:2px solid transparent;border-radius:14px;background:white;cursor:pointer}.sticker-options button.selected{border-color:#c29642;background:#fff4d5}.sticker-options button:focus-visible{outline:3px solid #409eff}@media(max-width:600px){.comments{padding:14px}.sticker-options{display:grid;grid-template-columns:1fr 1fr;gap:8px}.sticker-options button{padding:8px 0}}</style>
